@ProductManagement.API_HostAddress = http://localhost:5068

Post {{ProductManagement.API_HostAddress}}/api/Product/add-price
Content-Type: application/json
Accept: application/json
{
  "ProductId" : 3,
   "Price" : "2000",
   "fromDate": "2025-01-01",
  "toDate": "2025-06-30"
}



