@ProductManagement.API_HostAddress = http://localhost:5068

Post {{ProductManagement.API_HostAddress}}/api/Invoice
Content-Type: application/json
Accept: application/json
{
  "CustomerId": 6,
  "Items": [
    {
      "ProductId": 1008,
      "Quantity": 3
    }
  ]
}



